### PR TITLE
Bump dagre and update lock

### PR DESCRIPTION
**Pull request by princemaple**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:
Bump dagre (it used to require lodash^3 now it's on 4, which everybody uses)
And run npm install to update the lock (it's outdated, was still showing version 4.3)

**What is the current behavior?** (You can also link to an open issue here)
N/A

**What is the new behavior?**
N/A

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**: Please make a patch release if it's merged :)

### CODE REVIEW

**Comment by princemaple** [comment]
FYI @marjan-georgiev

**Comment by marjan-georgiev** [comment]
Thank you!

**Comment by marjan-georgiev** [comment]
released 5.0.1

**Comment by princemaple** [comment]
Great, thank you!

**Pull request merged**
