### PR TITLE
chore: add angular 17 to dependencies

### PR DESCRIPTION
**Pull request by Kr0san89**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

Angular 17 not allowed

**What is the new behavior?**
Allow Angular 17

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by argalasjr — APPROVED** [review]

**Review by Moalpima — APPROVED** [review]

**Comment by Malwinderkaur** [comment]
@marjan-georgiev  could we please get release for this PR. Currently the library is not working with Angular 17

**Review by Malwinderkaur — APPROVED** [review]

**Comment by Malwinderkaur** [comment]
@marjan-georgiev change is still not available in latest release, its not working with Angular 17

**Review by michellekontoff — APPROVED** [review]

**Comment by vbenavides** [comment]
It's not working with Angular 17, release this PR pls.

**Comment by Kr0san89** [comment]
as nobobdy is responding anymore i created a package for ng17 here https://www.npmjs.com/package/@kr0san89/ngx-graph
With the bad effect that when you use it you have to change your imports.

sorry that the readme and so on is still wrong, but i didn't want to invest to much time and i still hope that they will merge contributions from the community again :) or let ppl from the community help with it

**Review by RamiKassouf — APPROVED** [review]

**Review by HerrSpeucks — APPROVED** [review]

**Review by amitkachi — APPROVED** [review]

**Comment by steveblue** [comment]
ngx-graph 9.0.1 should support Angular 17. Please reopen if you see issues. Closing.

**Pull request closed without merging**
