### PR TITLE
chore: allow Angular 16

### PR DESCRIPTION
**Pull request by Kr0san89**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/swimlane/ngx-graph/issues/481

**What is the new behavior?**

Allow Angular 16

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by ChristopherVR** [comment]
Is it possible to merge this? Would love to have Angular 16 support.

**Comment by calhall** [comment]
@marjan-georgiev do you happen to have any idea as to when we'll be able to merge this? Looking forward to being able to play around on Angular 15/16 🚀

**Comment by bazobehram** [comment]
is there any news? we are waiting for the compatible version.

**Comment by bsarkadi** [comment]
Any updates about when a new release with Angular 16 support is planned?

**Review by marjan-georgiev — APPROVED** [review]

**Comment by steveblue** [comment]
Adding support for Angular 16 as a peer dependency shipped in 8.2.0 🎉

**Pull request merged**
