### PR TITLE
Variable node sizes and expose model for external developer

### PR DESCRIPTION
**Pull request by frozenplanet14**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
All the nodes generated have fixed sizes and models are not exposed through public api to be used by external developers.

**What is the new behavior?**
Nodes can be defined of variable sizes and models can be imported from the package.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
package.json can be ignored while merging. I was running into issue while downloading the packages thus changed the package version for the fix.
node

### CODE REVIEW

**Comment by assafsun** [comment]
I pushed support for different size nodes to version 5.x if it helps

**Comment by assafsun** [comment]
@frozenplanet14, a general question, which line curve did you used? looks interesting :)

**Comment by assafsun** [comment]
@frozenplanet14  Thanks for the reply.

Are you using ngx-graph 5.x version (install from the npm package) or using the master branch?

**Comment by frozenplanet14** [comment]
@assafsun I am using the master branch...

**Pull request closed without merging**
