### PR TITLE
chore: update d3 dependencies

### PR DESCRIPTION
**Pull request by Kr0san89**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/swimlane/ngx-graph/issues/500
https://github.com/swimlane/ngx-graph/issues/496
https://github.com/swimlane/ngx-graph/issues/495

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [x] Yes 
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
no IE, min node v12, maybe other

**Other information**:
Hard to test would recommend publishing it as some unstable version, so that people can try it

### CODE REVIEW

**Comment by krishna217** [comment]
@steveblue can you help ?

**Comment by Kr0san89** [comment]
@marjan-georgiev can you have a check?

**Comment by Kr0san89** [comment]
@jogaj @marjan-georgiev @steveblue can anybody check the PR. I think some people are needing it

**Comment by labeled** [comment]
Any status update on this, we're upgrading our Angular version and this is the only thing causing us to use legacy peer deps. And legacy peer deps creates a completely different package-lock.json. It seems a shame this PR has been open for ~3 months with no status updates.

**Review by labeled — APPROVED** [review]

**Comment by lazaro3487** [comment]
Is there any update for this PR? It would be nice to be merged.

**Comment by Kr0san89** [comment]
if you need it for security reasons you can try this package: https://www.npmjs.com/package/@kr0san89/ngx-graph/v/9.0.0-next-1

**Comment by jaykumarc** [comment]
Can someone please approve and merge this request please ? We are actually blocked by this. Thanks !

**Comment by jaykumarc** [comment]
Very humble request to @jogaj  @marjan-georgiev @steveblue  to kindly review and merge @Kr0san89 's PR. We need to push the application to production and it will be nice to have this solution applied rather than applying workarounds for the issue. Thank you !

**Comment by steveblue** [comment]
Thank you for the contribution and apologies for the difficulty this has caused. 

@swimlane/ngx-graph is now on 2.3.0. Can you please update the PR to reflect this change in the package.json?

**Comment by jaykumarc** [comment]
Thank you so @steveblue  for you attention. @Kr0san89 Kindly requesting you to please sync your branch with master, so that Stephen can merge it.
Thanks again !

**Comment by Kr0san89** [comment]
> Thank you for the contribution and apologies for the difficulty this has caused.
> 
> @swimlane/ngx-graph is now on 2.3.0. Can you please sync with master to reflect this change in the package.json?

There was no conflict so i think rebase was not really necassary, but still i did it. 
Will you merge further PRs?

**Comment by jaykumarc** [comment]
Thank you so much @Kr0san89 for this. @steveblue can you please do the needful now ? Thanks !

**Comment by jaykumarc** [comment]
Hi @steveblue @jogaj and @marjan-georgiev . Can you please complete this pull request and release new version for ngx-graph please ? We are actually stuck due to this. Thanks

**Pull request closed without merging**
