### PR TITLE
Bump mermaid from 8.13.3 to 8.13.8

### PR DESCRIPTION
**Pull request by shoeb8997**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ x] Other... Please describe:changing mermaid version from 8.13.3 to 8.13.8 to resolve vulnerability issue.

**What is the current behavior?** (You can also link to an open issue here)
Upgrade mermaid in ngx-graph

Impact
Malicious diagrams can contain javascript code that can be run at diagram readers machines.

Patches
The users should upgrade to version 8.13.8

Workarounds
You need to upgrade in order to avoid this issue.

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [ x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by marjan-georgiev** [comment]
Looks like prettier needs to be run

**Comment by shoeb8997** [comment]
> Looks like prettier needs to be run

I did run the prettier on package-lock.json, but there are no changes.

**Comment by marjan-georgiev** [comment]
@shoeb8997 can we also bump these dependencies (or their respective root dependencies) in package.json? Bumping them only in package-lock could easily get the reverted next time we run npm install.

**Comment by shoeb8997** [comment]
> @shoeb8997 can we also bump these dependencies (or their respective root dependencies) in package.json? Bumping them only in package-lock could easily get the reverted next time we run npm install.

done

**Pull request merged**
