### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by chabb**
D3-scale is used in this package; if it's not specified there and not installed in consumers projects, the build of those projects will fail

**What kind of change does this PR introduce?** (check one with "x")
- [X ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [X ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by sweeneki — CHANGES_REQUESTED** [review]
Change de to d3

**Comment by chabb** [comment]
Sorry for the typo, I've done it a bit too fast. Fixed

**Review by marjan-georgiev — CHANGES_REQUESTED** [review]
Thanks! Can we run `npm install` inside the project os package-lock.json is also updated please?

**Comment by spaque99** [comment]
Is this related to this other pull request: https://github.com/swimlane/ngx-graph/pull/430

Does it solve the issue where when using the latest version it is missing the d3-scale dependency?

**Comment by marjan-georgiev** [comment]
Closing this one, as it should be resolved by https://github.com/swimlane/ngx-graph/pull/430

**Pull request closed without merging**
