### PR TITLE
(release): 8.0.4

### PR DESCRIPTION
**Pull request by abiiiiiii**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

Release of new version 8.0.4 which contains peer dependencies for Angular 15

### CODE REVIEW

**Comment by abiiiiiii** [comment]
@marjan-georgiev would be great if you could also release the change with the angular 15 peer dependencies - thanks!

Kind regards
Joel

**Review by Malwinderkaur — APPROVED** [review]

**Comment by Malwinderkaur** [comment]
@marjan-georgiev could you please help in releasing this for support for Angular 15

**Review by rogerwesterbo — APPROVED** [review]
What could possibly go wrong?!

**Comment by rogerwesterbo** [comment]
image
need this pull request ...

**Comment by tzachs** [comment]
@abiiiiiii  / @Malwinderkaur  / @rogerwesterbo can you please help with releasing this?
We really need this,

Thanks

**Comment by rogerwesterbo** [comment]
@tzachs I need it myself, but this is taking too long... I am thinking about using another library instead ...

**Comment by rogerwesterbo** [comment]
> @marjan-georgiev please we need you :)

What is the plan for this library? And when? 😄

**Comment by jomaendle** [comment]
Any news on when can we expect this to be released? We really need the Angular 15 support 🙏

**Comment by UrkoLekuona** [comment]
Is this project still alive?

**Pull request closed without merging**
