### PR TITLE
Automatically center the graph in the viewport

### PR DESCRIPTION
**Pull request by jawadst**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Rendering a graph at the origin (0, 0)
https://github.com/swimlane/ngx-graph/issues/25

**What is the new behavior?**
Add an option (`autoCenter`) to automatically center the graph in the viewport. The default is set to false that the PR does not break anything.
It also adds a `center` function that can be called at any time to center the graph in the viewport.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by isaacplmann** [comment]
Also, a good idea, but it doesn't seem to work with Auto Zoom.

Open the demo and check Auto Zoom and Auto Center.  It looks like this:
screen shot 2018-03-02 at 4 09 59 pm

**Comment by bdiesel** [comment]
I think you can fix this by just multiplying the graphDims width and height by the zoomLevel scale factor.  I'll create a new pull request based of the latest master.

**Comment by bdiesel** [comment]
I added a commit fa5b03d.  I had to merge the master so I added this in my own fork.  Please let me know if you would like me to commit this to  @jawadst 's auto-center branch instead.

**Comment by jawadst** [comment]
Thanks @bdiesel

**Comment by isaacplmann** [comment]
@bdiesel Thanks for helping out.  Can you either commit to @jawadst branch (with the merges from master) or open another PR?  That will make it easier for us to verify the change and then merge it in.

**Comment by jawadst** [comment]
@isaacplmann I have rebased and updated my branch with @bdiesel's changes
I have also moved zoom/center options to the "Position and Zoom" tab in the demo (instead of "Dimensions").

**Comment by marjan-georgiev** [comment]
Looks good! @jawadst @bdiesel thank you for the contribution! Will release shortly.

**Comment by 1993alexey** [comment]
How would I call the `center()` method?

**Pull request merged**
