### PR TITLE
Link label not update when only label changed

### PR DESCRIPTION
**Pull request by freemanlam**
**What kind of change does this PR introduce?** (check one with "x")
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
When change only the label of link, the label text won't update on graph. (https://github.com/swimlane/ngx-graph/issues/100)

**What is the new behavior?**
Change label text, then the label on graph also updated.

**Does this PR introduce a breaking change?** (check one with "x")
- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by assafsun** [comment]
I tested the changes on version 5.x and the graph is not loading due to errors.
Let me know if I missed something

In general. the main problem is the use of internal links object that assign the values from the input bindings of the user links. The label itself is a string so it doesn't get updated when the user update it.

**Comment by freemanlam** [comment]
> I tested the changes on version 5.x and the graph is not loading due to errors.
> Let me know if I missed something
> 
> In general. the main problem is the use of internal links object that assign the values from the input bindings of the user links. The label itself is a string so it doesn't get updated when the user update it.
> 
> [update]
> I noticed that the changed code is relevant only for version 6

You mean the version of Angular or ngx-graph?

Btw, for more into, here is the link I reproduced the issue: [](https://stackblitz.com/edit/ngx-graph-issue-tw1vxc)
When only change text, the label won't update.

**Comment by assafsun** [comment]
@marjan-georgiev  it will not work with 5.x version. the code rely on the tick function which don't exists.
When I tested it, the graph had problems to load.

@freemanlam, I meant ngx-graph version.
As a workaround you can define an object on the link and place a label variable in it.
Ignore the label value as the example has.

**Comment by assafsun** [comment]
@freemanlam I think we can close this PR due to the following reasons:

1. You can set the label inside an object which will be on the node and as a result, each update
will be updated also on the graph.
The object can contains additional information which you can use beside the label.

2. We will insert the label copy (or change the example IMO) to version 6 once it will be release.

What do you think?

cc: @marjan-georgiev

**Comment by assafsun** [comment]
Closing this PR.
Please update me for any issue.

**Pull request closed without merging**
