### PR TITLE
Chore/update angular to 17

### PR DESCRIPTION
**Pull request by Kr0san89**
**What kind of change does this PR introduce?** (check one with "x")
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**
new angular version

**Does this PR introduce a breaking change?** (check one with "x")
- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
only angular 17
the documentation system has some issues (need updates there too)

**Other information**:

### CODE REVIEW

**Review by mok-camos — APPROVED** [review]

**Comment by DeepakGMTT** [comment]
hi @marjan-georgiev i'm using this package for my project can we please priority this PR.

**Comment by mayurmuley1412** [comment]
> hi @marjan-georgiev i'm using this package for my project can we please priority this PR. Can we have the time line when this PR will be merged?

I am also waiting for the merge and release. @Kr0san89 Can you check conflicts and merge this PR since its approved.

**Comment by Kr0san89** [comment]
> > hi @marjan-georgiev i'm using this package for my project can we please priority this PR. Can we have the time line when this PR will be merged?
> 
> I am also waiting for the merge and release. @Kr0san89 Can you check conflicts and merge this PR since its approved.

Sadly i can not the approvement has to come from a person with "write access" which is not the case yet. It is not even clear if they want to merge this PR at some stage. As i have another PR open for over a year https://github.com/swimlane/ngx-graph/pull/513 i got a bit more carefull how i invest my time here.

If there is a comment from someone who can merge that they will i would do it, but until then i'll wait.

But this PR will not bring you much benefit other than "smaller bundle"

**Review by MaxTotal — APPROVED** [review]

**Comment by steveblue** [comment]
ngx-graph 9.0.0 supports Angular 18.

**Comment by DeepakGMTT** [comment]
[like]  Deepak Markandan reacted to your message:
________________________________

**Comment by DeepakGMTT** [comment]
[celebrate]     Deepak Markandan reacted to your message:
________________________________

**Pull request closed without merging**
